[package]
name = "jlox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
run = ["dep:libtcc"]

[dependencies]
libtcc = { version = "0.2.0", optional = true }
